language: python
python:
  - "3.5"
dist: trusty
sudo: required
env:
before_install:
  # Automatic publishing to GitHub Pages from Travis CI
  - openssl aes-256-cbc -K $encrypted_8c9178467c7c_key -iv $encrypted_8c9178467c7c_iv -in publish-key.enc -out ~/.ssh/publish-key -d
  - chmod u=rw,og= ~/.ssh/publish-key
  - echo "Host github.com" >> ~/.ssh/config
  - echo "  StrictHostKeyChecking no" >> ~/.ssh/config
  - echo "  IdentityFile ~/.ssh/publish-key" >> ~/.ssh/config
  - git remote set-url origin git@github.com:zolware/specsPonteligo.git
  - git fetch origin -f gh-pages:gh-pages
install:
  # command to install dependencies
  - pip install --upgrade wheel setuptools pip ghp-import
  - pip install -r requirements.txt
script:
  - mkdir -p build && cd build
  - cmake ..
  - pip install ghp-import
  - make doc
  - ghp-import -n -p -m "Update gh-pages." doc/_build/ponteligo/
